global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'heart-disease-api'
    static_configs:
      - targets: ['heart-disease-api:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
